apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-blackscholes
  labels:
    name: parsec-blackscholes
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:blackscholes-native-reduced
        name: parsecblackscholes
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/parsecmgmt -a run -p blackscholes -i native -n 14"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
